package com.team1091.tanks

const val TIME_TO_FIRE = 2.0
const val TANK_BARREL_LENGTH = 9.0
const val TANK_PICKUP_RADIUS = 8.0
const val TANK_RADIUS = 8.0
const val TANK_SPEED = 8.0
const val TURRET_TURN_RATE = 1.0
const val TANK_TURN_RATE = 1.0

const val PROJECTILE_VELOCITY: Double = 30.0
const val PROJECTILE_MAX_FLIGHT_TIME = 5.0
const val PROJECTILE_MAX_FLIGHT_DIST = PROJECTILE_VELOCITY * PROJECTILE_MAX_FLIGHT_TIME